name: Trigger auto deployment for container-app-n35v2joszmu5o

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-n35v2joszmu5o-AutoDeployTrigger-faec8c35-f4de-4405-a720-61a1a430565e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPN35V2JOSZMU5O_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPN35V2JOSZMU5O_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPN35V2JOSZMU5O_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPN35V2JOSZMU5O_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPN35V2JOSZMU5O_REGISTRY_PASSWORD }}
          containerAppName: container-app-n35v2joszmu5o
          resourceGroup: expresssamplebf899a68
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


